chore: Update ECS Service deployment workflow to handle update failure

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -67,6 +67,7 @@ jobs:
           echo "digest=$IMAGE_DIGEST" >> $GITHUB_ENV
 
       - name: Register New Task Definition
+        id: register_task_definition
         run: |
           TASK_DEFINITION=$(cat <<EOF
           {
@@ -124,36 +125,38 @@ jobs:
           )
 
           echo "$TASK_DEFINITION" > new_task_definition.json
+          register_output=$(aws ecs register-task-definition --cli-input-json file://new_task_definition.json 2>&1) || register_status=$?
+          echo "register_output=$register_output" >> $GITHUB_ENV
+          if [ -z "$register_status" ]; then
+            echo "register_status=success" >> $GITHUB_ENV
+          else
+            echo "register_status=failure" >> $GITHUB_ENV
+            exit 1
+          fi
+        shell: bash
 
-          aws ecs register-task-definition --cli-input-json file://new_task_definition.json
-
-      # - name: Update ECS Service
-      #   run: |
-      #     NEW_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition go-pro-app-task --query 'taskDefinition.taskDefinitionArn' --output text)
-      #     aws ecs update-service --cluster go-pro-app-cluster --service go-pro-app-service --task-definition $NEW_TASK_DEFINITION_ARN
       - name: Update ECS Service
+        if: ${{ env.register_status == 'success' }}
         id: update_ecs
         run: |
-            set -e
-            NEW_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition go-pro-app-task --query 'taskDefinition.taskDefinitionArn' --output text)
-            update_output=$(aws ecs update-service --cluster go-pro-app-cluster --service go-pro-app-service --task-definition $NEW_TASK_DEFINITION_ARN 2>&1) || update_status=$?
-            echo "update_output=$update_output" >> $GITHUB_ENV
-            if [ -z "$update_status" ]; then
-              echo "service_update_status=success" >> $GITHUB_ENV
-            else
-              echo "service_update_status=failure" >> $GITHUB_ENV
-              echo "update_status=$update_status" >> $GITHUB_ENV
-            fi
+          NEW_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition go-pro-app-task --query 'taskDefinition.taskDefinitionArn' --output text)
+          update_output=$(aws ecs update-service --cluster go-pro-app-cluster --service go-pro-app-service --task-definition $NEW_TASK_DEFINITION_ARN 2>&1) || update_status=$?
+          echo "update_output=$update_output" >> $GITHUB_ENV
+          if [ -z "$update_status" ]; then
+            echo "update_status=success" >> $GITHUB_ENV
+          else
+            echo "update_status=failure" >> $GITHUB_ENV
+            exit 1
+          fi
         shell: bash
-        
+
       - name: Check ECS Service Update Status
-        if: ${{ env.service_update_status == 'success' }}
+        if: ${{ env.update_status == 'success' }}
         run: echo "ECS Service update was successful."
-        
+
       - name: Handle ECS Service Update Failure
-        if: ${{ env.service_update_status == 'failure' }}
+        if: ${{ env.update_status == 'failure' }}
         run: |
-            echo "ECS Service update failed with status ${{ env.update_status }}."
-            echo "Error output:"
-            echo "${{ env.update_output }}"
-        
+          echo "ECS Service update failed."
+          echo "Error output:"
+          echo "${{ env.update_output }}"
