chore: Update ECS Service deployment workflow to handle update failure

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -127,7 +127,33 @@ jobs:
 
           aws ecs register-task-definition --cli-input-json file://new_task_definition.json
 
+      # - name: Update ECS Service
+      #   run: |
+      #     NEW_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition go-pro-app-task --query 'taskDefinition.taskDefinitionArn' --output text)
+      #     aws ecs update-service --cluster go-pro-app-cluster --service go-pro-app-service --task-definition $NEW_TASK_DEFINITION_ARN
       - name: Update ECS Service
+        id: update_ecs
         run: |
-          NEW_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition go-pro-app-task --query 'taskDefinition.taskDefinitionArn' --output text)
-          aws ecs update-service --cluster go-pro-app-cluster --service go-pro-app-service --task-definition $NEW_TASK_DEFINITION_ARN
+            set -e
+            NEW_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition go-pro-app-task --query 'taskDefinition.taskDefinitionArn' --output text)
+            update_output=$(aws ecs update-service --cluster go-pro-app-cluster --service go-pro-app-service --task-definition $NEW_TASK_DEFINITION_ARN 2>&1) || update_status=$?
+            echo "update_output=$update_output" >> $GITHUB_ENV
+            if [ -z "$update_status" ]; then
+              echo "service_update_status=success" >> $GITHUB_ENV
+            else
+              echo "service_update_status=failure" >> $GITHUB_ENV
+              echo "update_status=$update_status" >> $GITHUB_ENV
+            fi
+        shell: bash
+        
+      - name: Check ECS Service Update Status
+        if: ${{ env.service_update_status == 'success' }}
+        run: echo "ECS Service update was successful."
+        
+      - name: Handle ECS Service Update Failure
+        if: ${{ env.service_update_status == 'failure' }}
+        run: |
+            echo "ECS Service update failed with status ${{ env.update_status }}."
+            echo "Error output:"
+            echo "${{ env.update_output }}"
+        
